services:
  - type: web
    name: confirmacion-app
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port $PORT --server.address 0.0.0.0
    envVars:
      - key: GOOGLE_APPLICATION_CREDENTIALS
        value: credentials.json
